
##################   FORGET PASSWORD   ########################


########   register user  #############
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "name": "hello",
    "email": "hello@gmail.com",
    "password": "hello"
}

########   email verification  ##########
POST http://localhost:5000/user/email-verify
Content-Type: application/json

{
      "email": "hello@gmail.com"
}


########  reset password   #########
POST http://localhost:5000/user/reset-password/3729e627-5b97-4744-a73d-ddf2665c8cf4
Content-Type: application/json

{
      "password": "user1234"
}


#######  get product  #######
GET http://localhost:5000/Product


####### POST product  ######
POST http://localhost:5000/Product
Content-Type: application/json

{
  "product_name": "Table",
  "product_description": "bad product",
  "product_price": "100paisa",
  "product_intro_date": "02/03/2000",
  "GST": "22",
  "product_inventry_flag": false
}



##########  GET customers  ######
GET http://localhost:5000/Customer


#########  POST customer   #######
POST http://localhost:5000/Customer
Content-Type: application/json

{
  "customer_name": "Prasun",
  "customer_address": "RR 222",
  "customer_phone": 9000093253,
  "GST": "40p",
  "PAN": "hsfgsdyugayud"
}


#########  DELETE customer  ###########
DELETE http://localhost:5000/Customer/606b162efdc0b54e64bf859e



###############   Allocation   ############

#########   get allocation of customer and product  #######
GET http://localhost:5000/Allocation



#######   post allocation of customer and product   #############
POST  http://localhost:5000/Allocation
Content-Type: application/json

{
      "customerId": "606b12a1fdc0b54e64bf859d",
      "productId": "606b035cb5186e10e8f72709"
}

######  delete allocation of customers and products  ########
DELETE http://localhost:5000/Allocation/606b193a3b696942e0a2d3b1