
##################   FORGET PASSWORD   ########################


########   register user  #############
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "name": "hello",
    "email": "hello@gmail.com",
    "password": "hello"
}

########   email verification  ##########
POST http://localhost:5000/user/email-verify
Content-Type: application/json

{
      "email": "hello@gmail.com"
}


########  reset password   #########
POST http://localhost:5000/user/reset-password/3729e627-5b97-4744-a73d-ddf2665c8cf4
Content-Type: application/json

{
      "password": "user1234"
}


#######  get product  #######
GET http://localhost:5000/Product


####### POST product  ######
POST http://localhost:5000/Product
Content-Type: application/json

{
  "product_name": "Table",
  "product_description": "bad product",
  "product_price": "100paisa",
  "product_intro_date": "02/03/2000",
  "GST": "22",
  "product_inventry_flag": false
}


